[workspace]
authors = ["nkrchak <noah-krchak@uiowa.edu>"]
channels = ["conda-forge"]
name = "SimpleITK-Notebooks"
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
simpleitk = ">2.2.1"
jupyter = "*"
matplotlib = "*"
ipywidgets = "*"
ipympl = "*"
numpy = "*"
scipy = "*"
pandas = "*"
numba = "*"
multiprocess = "*"
tqdm = "*"
requests = "*"

[feature.dev.pypi-dependencies]
black = { version = "*", extras = ["jupyter"] }
pytest = "*"
markdown = "*"
lxml = "*"
pyenchant = "*"
ipython = "<=8.12"

[environments]
dev = { features = ["dev"], no-default-feature = true }
